# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'contact.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ContactWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(539, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 521, 541))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.nom_prenom = QtGui.QLineEdit(self.groupBox)
        self.nom_prenom.setGeometry(QtCore.QRect(122, 20, 91, 21))
        self.nom_prenom.setObjectName(_fromUtf8("nom_prenom"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.adresse_perso = QtGui.QLineEdit(self.groupBox)
        self.adresse_perso.setGeometry(QtCore.QRect(120, 54, 91, 20))
        self.adresse_perso.setObjectName(_fromUtf8("adresse_perso"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cp_ville_pays = QtGui.QLineEdit(self.groupBox)
        self.cp_ville_pays.setGeometry(QtCore.QRect(120, 88, 91, 21))
        self.cp_ville_pays.setText(_fromUtf8(""))
        self.cp_ville_pays.setObjectName(_fromUtf8("cp_ville_pays"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.telephone = QtGui.QLineEdit(self.groupBox)
        self.telephone.setGeometry(QtCore.QRect(122, 118, 91, 21))
        self.telephone.setText(_fromUtf8(""))
        self.telephone.setObjectName(_fromUtf8("telephone"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.email_contact = QtGui.QLineEdit(self.groupBox)
        self.email_contact.setGeometry(QtCore.QRect(122, 150, 231, 21))
        self.email_contact.setObjectName(_fromUtf8("email_contact"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.entreprise_associee_1 = QtGui.QLineEdit(self.groupBox)
        self.entreprise_associee_1.setGeometry(QtCore.QRect(182, 188, 171, 21))
        self.entreprise_associee_1.setObjectName(_fromUtf8("entreprise_associee_1"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 151, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(8, 222, 151, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.entreprise_associee_2 = QtGui.QLineEdit(self.groupBox)
        self.entreprise_associee_2.setGeometry(QtCore.QRect(180, 220, 171, 21))
        self.entreprise_associee_2.setObjectName(_fromUtf8("entreprise_associee_2"))
        self.Remarques = QtGui.QTextEdit(self.groupBox)
        self.Remarques.setGeometry(QtCore.QRect(130, 250, 371, 64))
        self.Remarques.setObjectName(_fromUtf8("Remarques"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 250, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Button_tout = QtGui.QRadioButton(self.groupBox)
        self.Button_tout.setGeometry(QtCore.QRect(190, 320, 61, 20))
        self.Button_tout.setObjectName(_fromUtf8("Button_tout"))
        self.par_genre = QtGui.QRadioButton(self.groupBox)
        self.par_genre.setGeometry(QtCore.QRect(260, 320, 71, 20))
        self.par_genre.setObjectName(_fromUtf8("par_genre"))
        self.choix_genre = QtGui.QScrollArea(self.groupBox)
        self.choix_genre.setGeometry(QtCore.QRect(339, 320, 161, 41))
        self.choix_genre.setWidgetResizable(True)
        self.choix_genre.setObjectName(_fromUtf8("choix_genre"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 157, 37))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.choix_genre.setWidget(self.scrollAreaWidgetContents)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 320, 141, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.titre_livre = QtGui.QLineEdit(self.groupBox)
        self.titre_livre.setGeometry(QtCore.QRect(230, 390, 91, 21))
        self.titre_livre.setObjectName(_fromUtf8("titre_livre"))
        self.label_11 = QtGui.QLabel(self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(118, 390, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.SP = QtGui.QCheckBox(self.groupBox)
        self.SP.setGeometry(QtCore.QRect(20, 390, 87, 20))
        self.SP.setObjectName(_fromUtf8("SP"))
        self.contact = QtGui.QRadioButton(self.groupBox)
        self.contact.setGeometry(QtCore.QRect(20, 420, 81, 20))
        self.contact.setObjectName(_fromUtf8("contact"))
        self.entreprise = QtGui.QRadioButton(self.groupBox)
        self.entreprise.setGeometry(QtCore.QRect(110, 420, 111, 20))
        self.entreprise.setObjectName(_fromUtf8("entreprise"))
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.groupBox)
        self.dateTimeEdit.setGeometry(QtCore.QRect(310, 420, 194, 21))
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(10, 19, 501, 161))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_2 = QtGui.QFrame(self.groupBox)
        self.frame_2.setGeometry(QtCore.QRect(9, 179, 501, 191))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.frame_3 = QtGui.QFrame(self.groupBox)
        self.frame_3.setGeometry(QtCore.QRect(10, 370, 501, 81))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 539, 23))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Contact", None))
        self.label.setText(_translate("MainWindow", "Nom prénom", None))
        self.label_2.setText(_translate("MainWindow", "Adresse perso", None))
        self.label_3.setText(_translate("MainWindow", "CP, Ville, Pays", None))
        self.label_4.setText(_translate("MainWindow", "Téléphone", None))
        self.label_5.setText(_translate("MainWindow", "email", None))
        self.label_6.setText(_translate("MainWindow", "Entreprise associée 1", None))
        self.label_7.setText(_translate("MainWindow", "Entreprise associée 2", None))
        self.label_8.setText(_translate("MainWindow", "Remarques", None))
        self.Button_tout.setText(_translate("MainWindow", "Tout", None))
        self.par_genre.setText(_translate("MainWindow", "Genre", None))
        self.label_9.setText(_translate("MainWindow", "Envoi systématique", None))
        self.label_11.setText(_translate("MainWindow", "Titre du livre", None))
        self.SP.setText(_translate("MainWindow", "SP", None))
        self.contact.setText(_translate("MainWindow", "contact", None))
        self.entreprise.setText(_translate("MainWindow", "entreprise", None))

