# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt_gest_envoi_livres.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(586, 692)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gestEnvoi = QtGui.QTabWidget(self.centralwidget)
        self.gestEnvoi.setGeometry(QtCore.QRect(10, 0, 561, 601))
        self.gestEnvoi.setObjectName(_fromUtf8("gestEnvoi"))
        self.Entreprises = QtGui.QWidget()
        self.Entreprises.setObjectName(_fromUtf8("Entreprises"))
        self.groupBox = QtGui.QGroupBox(self.Entreprises)
        self.groupBox.setGeometry(QtCore.QRect(30, 20, 521, 541))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.nom_prenom = QtGui.QLineEdit(self.groupBox)
        self.nom_prenom.setGeometry(QtCore.QRect(122, 20, 91, 21))
        self.nom_prenom.setObjectName(_fromUtf8("nom_prenom"))
        self.label = QtGui.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.adresse_perso = QtGui.QLineEdit(self.groupBox)
        self.adresse_perso.setGeometry(QtCore.QRect(120, 54, 91, 20))
        self.adresse_perso.setObjectName(_fromUtf8("adresse_perso"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 60, 91, 20))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.cp_ville_pays = QtGui.QLineEdit(self.groupBox)
        self.cp_ville_pays.setGeometry(QtCore.QRect(120, 88, 91, 21))
        self.cp_ville_pays.setText(_fromUtf8(""))
        self.cp_ville_pays.setObjectName(_fromUtf8("cp_ville_pays"))
        self.label_3 = QtGui.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.telephone = QtGui.QLineEdit(self.groupBox)
        self.telephone.setGeometry(QtCore.QRect(122, 118, 91, 21))
        self.telephone.setText(_fromUtf8(""))
        self.telephone.setObjectName(_fromUtf8("telephone"))
        self.label_4 = QtGui.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.email_entreprise = QtGui.QLineEdit(self.groupBox)
        self.email_entreprise.setGeometry(QtCore.QRect(122, 150, 231, 21))
        self.email_entreprise.setObjectName(_fromUtf8("email_entreprise"))
        self.label_5 = QtGui.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.nom_prenom_contact_1 = QtGui.QLineEdit(self.groupBox)
        self.nom_prenom_contact_1.setGeometry(QtCore.QRect(182, 268, 171, 21))
        self.nom_prenom_contact_1.setObjectName(_fromUtf8("nom_prenom_contact_1"))
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 270, 151, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(8, 302, 151, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.nom_prenom_contact_2 = QtGui.QLineEdit(self.groupBox)
        self.nom_prenom_contact_2.setGeometry(QtCore.QRect(180, 300, 171, 21))
        self.nom_prenom_contact_2.setObjectName(_fromUtf8("nom_prenom_contact_2"))
        self.Remarques = QtGui.QTextEdit(self.groupBox)
        self.Remarques.setGeometry(QtCore.QRect(130, 330, 371, 64))
        self.Remarques.setObjectName(_fromUtf8("Remarques"))
        self.label_8 = QtGui.QLabel(self.groupBox)
        self.label_8.setGeometry(QtCore.QRect(10, 330, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.Button_tout = QtGui.QRadioButton(self.groupBox)
        self.Button_tout.setGeometry(QtCore.QRect(190, 420, 61, 20))
        self.Button_tout.setObjectName(_fromUtf8("Button_tout"))
        self.par_genre = QtGui.QRadioButton(self.groupBox)
        self.par_genre.setGeometry(QtCore.QRect(260, 420, 71, 20))
        self.par_genre.setObjectName(_fromUtf8("par_genre"))
        self.choix_genre = QtGui.QScrollArea(self.groupBox)
        self.choix_genre.setGeometry(QtCore.QRect(340, 400, 161, 41))
        self.choix_genre.setWidgetResizable(True)
        self.choix_genre.setObjectName(_fromUtf8("choix_genre"))
        self.scrollAreaWidgetContents = QtGui.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 159, 39))
        self.scrollAreaWidgetContents.setObjectName(_fromUtf8("scrollAreaWidgetContents"))
        self.choix_genre.setWidget(self.scrollAreaWidgetContents)
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(20, 420, 141, 16))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.frame = QtGui.QFrame(self.groupBox)
        self.frame.setGeometry(QtCore.QRect(10, 20, 501, 231))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.frame_3 = QtGui.QFrame(self.groupBox)
        self.frame_3.setGeometry(QtCore.QRect(10, 460, 501, 71))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.frame_2 = QtGui.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(-10, -190, 501, 201))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.dateTimeEdit = QtGui.QDateTimeEdit(self.frame_3)
        self.dateTimeEdit.setGeometry(QtCore.QRect(300, 40, 194, 21))
        self.dateTimeEdit.setObjectName(_fromUtf8("dateTimeEdit"))
        self.label_10 = QtGui.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(8, 10, 91, 16))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.checkBox = QtGui.QCheckBox(self.frame_3)
        self.checkBox.setGeometry(QtCore.QRect(10, 40, 87, 20))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.entreprise = QtGui.QRadioButton(self.frame_3)
        self.entreprise.setGeometry(QtCore.QRect(200, 40, 111, 20))
        self.entreprise.setObjectName(_fromUtf8("entreprise"))
        self.titre_livre = QtGui.QLineEdit(self.frame_3)
        self.titre_livre.setGeometry(QtCore.QRect(220, 10, 91, 21))
        self.titre_livre.setObjectName(_fromUtf8("titre_livre"))
        self.contact = QtGui.QRadioButton(self.frame_3)
        self.contact.setGeometry(QtCore.QRect(110, 40, 81, 20))
        self.contact.setObjectName(_fromUtf8("contact"))
        self.label_11 = QtGui.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(108, 10, 91, 16))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.reprsentant = QtGui.QLineEdit(self.groupBox)
        self.reprsentant.setGeometry(QtCore.QRect(120, 180, 91, 21))
        self.reprsentant.setObjectName(_fromUtf8("reprsentant"))
        self.label_12 = QtGui.QLabel(self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 180, 91, 16))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.groupement = QtGui.QLineEdit(self.groupBox)
        self.groupement.setGeometry(QtCore.QRect(120, 210, 91, 21))
        self.groupement.setText(_fromUtf8(""))
        self.groupement.setObjectName(_fromUtf8("groupement"))
        self.label_13 = QtGui.QLabel(self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 210, 91, 16))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gestEnvoi.addTab(self.Entreprises, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_2)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 10, 521, 541))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.nom_prenom_2 = QtGui.QLineEdit(self.groupBox_2)
        self.nom_prenom_2.setGeometry(QtCore.QRect(122, 20, 91, 21))
        self.nom_prenom_2.setObjectName(_fromUtf8("nom_prenom_2"))
        self.label_14 = QtGui.QLabel(self.groupBox_2)
        self.label_14.setGeometry(QtCore.QRect(10, 30, 91, 16))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.adresse_perso_2 = QtGui.QLineEdit(self.groupBox_2)
        self.adresse_perso_2.setGeometry(QtCore.QRect(120, 54, 91, 20))
        self.adresse_perso_2.setObjectName(_fromUtf8("adresse_perso_2"))
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setGeometry(QtCore.QRect(10, 60, 91, 20))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.cp_ville_pays_2 = QtGui.QLineEdit(self.groupBox_2)
        self.cp_ville_pays_2.setGeometry(QtCore.QRect(120, 88, 91, 21))
        self.cp_ville_pays_2.setText(_fromUtf8(""))
        self.cp_ville_pays_2.setObjectName(_fromUtf8("cp_ville_pays_2"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setGeometry(QtCore.QRect(10, 90, 91, 16))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.telephone_2 = QtGui.QLineEdit(self.groupBox_2)
        self.telephone_2.setGeometry(QtCore.QRect(122, 118, 91, 21))
        self.telephone_2.setText(_fromUtf8(""))
        self.telephone_2.setObjectName(_fromUtf8("telephone_2"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.email_contact = QtGui.QLineEdit(self.groupBox_2)
        self.email_contact.setGeometry(QtCore.QRect(122, 150, 231, 21))
        self.email_contact.setObjectName(_fromUtf8("email_contact"))
        self.label_18 = QtGui.QLabel(self.groupBox_2)
        self.label_18.setGeometry(QtCore.QRect(10, 150, 91, 16))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.entreprise_associee_1 = QtGui.QLineEdit(self.groupBox_2)
        self.entreprise_associee_1.setGeometry(QtCore.QRect(182, 188, 171, 21))
        self.entreprise_associee_1.setObjectName(_fromUtf8("entreprise_associee_1"))
        self.label_19 = QtGui.QLabel(self.groupBox_2)
        self.label_19.setGeometry(QtCore.QRect(10, 190, 151, 16))
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.label_20 = QtGui.QLabel(self.groupBox_2)
        self.label_20.setGeometry(QtCore.QRect(8, 222, 151, 16))
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.entreprise_associee_2 = QtGui.QLineEdit(self.groupBox_2)
        self.entreprise_associee_2.setGeometry(QtCore.QRect(180, 220, 171, 21))
        self.entreprise_associee_2.setObjectName(_fromUtf8("entreprise_associee_2"))
        self.Remarques_2 = QtGui.QTextEdit(self.groupBox_2)
        self.Remarques_2.setGeometry(QtCore.QRect(130, 250, 371, 64))
        self.Remarques_2.setObjectName(_fromUtf8("Remarques_2"))
        self.label_21 = QtGui.QLabel(self.groupBox_2)
        self.label_21.setGeometry(QtCore.QRect(10, 250, 81, 16))
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.Button_tout_2 = QtGui.QRadioButton(self.groupBox_2)
        self.Button_tout_2.setGeometry(QtCore.QRect(190, 320, 61, 20))
        self.Button_tout_2.setObjectName(_fromUtf8("Button_tout_2"))
        self.par_genre_2 = QtGui.QRadioButton(self.groupBox_2)
        self.par_genre_2.setGeometry(QtCore.QRect(260, 320, 71, 20))
        self.par_genre_2.setObjectName(_fromUtf8("par_genre_2"))
        self.choix_genre_2 = QtGui.QScrollArea(self.groupBox_2)
        self.choix_genre_2.setGeometry(QtCore.QRect(339, 320, 161, 41))
        self.choix_genre_2.setWidgetResizable(True)
        self.choix_genre_2.setObjectName(_fromUtf8("choix_genre_2"))
        self.scrollAreaWidgetContents_2 = QtGui.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 159, 39))
        self.scrollAreaWidgetContents_2.setObjectName(_fromUtf8("scrollAreaWidgetContents_2"))
        self.choix_genre_2.setWidget(self.scrollAreaWidgetContents_2)
        self.label_22 = QtGui.QLabel(self.groupBox_2)
        self.label_22.setGeometry(QtCore.QRect(20, 320, 141, 16))
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.titre_livre_2 = QtGui.QLineEdit(self.groupBox_2)
        self.titre_livre_2.setGeometry(QtCore.QRect(230, 390, 91, 21))
        self.titre_livre_2.setObjectName(_fromUtf8("titre_livre_2"))
        self.label_23 = QtGui.QLabel(self.groupBox_2)
        self.label_23.setGeometry(QtCore.QRect(118, 390, 91, 16))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.SP = QtGui.QCheckBox(self.groupBox_2)
        self.SP.setGeometry(QtCore.QRect(20, 390, 87, 20))
        self.SP.setObjectName(_fromUtf8("SP"))
        self.contact_2 = QtGui.QRadioButton(self.groupBox_2)
        self.contact_2.setGeometry(QtCore.QRect(20, 420, 81, 20))
        self.contact_2.setObjectName(_fromUtf8("contact_2"))
        self.entreprise_2 = QtGui.QRadioButton(self.groupBox_2)
        self.entreprise_2.setGeometry(QtCore.QRect(110, 420, 111, 20))
        self.entreprise_2.setObjectName(_fromUtf8("entreprise_2"))
        self.dateTimeEdit_2 = QtGui.QDateTimeEdit(self.groupBox_2)
        self.dateTimeEdit_2.setGeometry(QtCore.QRect(310, 420, 194, 21))
        self.dateTimeEdit_2.setObjectName(_fromUtf8("dateTimeEdit_2"))
        self.frame_4 = QtGui.QFrame(self.groupBox_2)
        self.frame_4.setGeometry(QtCore.QRect(10, 19, 501, 161))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.frame_5 = QtGui.QFrame(self.groupBox_2)
        self.frame_5.setGeometry(QtCore.QRect(9, 179, 501, 191))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.frame_6 = QtGui.QFrame(self.groupBox_2)
        self.frame_6.setGeometry(QtCore.QRect(10, 370, 501, 81))
        self.frame_6.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_6.setObjectName(_fromUtf8("frame_6"))
        self.gestEnvoi.addTab(self.tab_2, _fromUtf8(""))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.label_24 = QtGui.QLabel(self.tab)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 101, 21))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gestEnvoi.addTab(self.tab, _fromUtf8(""))
        self.abandon = QtGui.QPushButton(self.centralwidget)
        self.abandon.setGeometry(QtCore.QRect(490, 620, 80, 22))
        self.abandon.setObjectName(_fromUtf8("abandon"))
        self.valide = QtGui.QPushButton(self.centralwidget)
        self.valide.setGeometry(QtCore.QRect(390, 620, 80, 22))
        self.valide.setObjectName(_fromUtf8("valide"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 19))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.gestEnvoi.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Entreprise", None))
        self.label.setText(_translate("MainWindow", "Raison sociale", None))
        self.label_2.setText(_translate("MainWindow", "Adresse perso", None))
        self.label_3.setText(_translate("MainWindow", "CP, Ville, Pays", None))
        self.label_4.setText(_translate("MainWindow", "Téléphone", None))
        self.label_5.setText(_translate("MainWindow", "email", None))
        self.label_6.setText(_translate("MainWindow", "Nom prénom contact 1", None))
        self.label_7.setText(_translate("MainWindow", "Nom prénom contact  2", None))
        self.label_8.setText(_translate("MainWindow", "Remarques", None))
        self.Button_tout.setText(_translate("MainWindow", "Tout", None))
        self.par_genre.setText(_translate("MainWindow", "Genre", None))
        self.label_9.setText(_translate("MainWindow", "Envoi systématique", None))
        self.label_10.setText(_translate("MainWindow", "Liste des SP", None))
        self.checkBox.setText(_translate("MainWindow", "envoyé", None))
        self.entreprise.setText(_translate("MainWindow", "entreprise", None))
        self.contact.setText(_translate("MainWindow", "contact", None))
        self.label_11.setText(_translate("MainWindow", "Titre du livre", None))
        self.label_12.setText(_translate("MainWindow", "Représentant", None))
        self.label_13.setText(_translate("MainWindow", "Groupement", None))
        self.gestEnvoi.setTabText(self.gestEnvoi.indexOf(self.Entreprises), _translate("MainWindow", "Tab 1", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Contact", None))
        self.label_14.setText(_translate("MainWindow", "Nom prénom", None))
        self.label_15.setText(_translate("MainWindow", "Adresse perso", None))
        self.label_16.setText(_translate("MainWindow", "CP, Ville, Pays", None))
        self.label_17.setText(_translate("MainWindow", "Téléphone", None))
        self.label_18.setText(_translate("MainWindow", "email", None))
        self.label_19.setText(_translate("MainWindow", "Entreprise associée 1", None))
        self.label_20.setText(_translate("MainWindow", "Entreprise associée 2", None))
        self.label_21.setText(_translate("MainWindow", "Remarques", None))
        self.Button_tout_2.setText(_translate("MainWindow", "Tout", None))
        self.par_genre_2.setText(_translate("MainWindow", "Genre", None))
        self.label_22.setText(_translate("MainWindow", "Envoi systématique", None))
        self.label_23.setText(_translate("MainWindow", "Titre du livre", None))
        self.SP.setText(_translate("MainWindow", "SP", None))
        self.contact_2.setText(_translate("MainWindow", "contact", None))
        self.entreprise_2.setText(_translate("MainWindow", "entreprise", None))
        self.gestEnvoi.setTabText(self.gestEnvoi.indexOf(self.tab_2), _translate("MainWindow", "Tab 2", None))
        self.label_24.setText(_translate("MainWindow", "Envoi de livre", None))
        self.gestEnvoi.setTabText(self.gestEnvoi.indexOf(self.tab), _translate("MainWindow", "Page", None))
        self.abandon.setText(_translate("MainWindow", "Abandon", None))
        self.valide.setText(_translate("MainWindow", "Valider", None))

